---

- name: Install pip
  package:
    name: python3-pip
    state: latest

- name: Upgrade pip
  pip:
    name: pip
    state: latest
    virtualenv: "{{ ansible_init_venv_path }}"

- name: Install Ansible
  pip:
    name:
      - ansible
      - jmespath
    state: latest
    virtualenv: "{{ ansible_init_venv_path }}"

- name: Install ansible-init script
  ansible.builtin.template:
    src: ansible-init.sh.j2
    dest: /usr/bin/ansible-init
    mode: +x

- name: Install systemd unit for ansible-init
  ansible.builtin.template:
    src: ansible-init.service.j2
    dest: /etc/systemd/system/ansible-init.service

- name: Ensure ansible-init service is enabled
  systemd:
    daemon_reload: yes
    name: ansible-init.service
    enabled: yes
  ignore_errors: yes
