---
- name: Install InfiniBand support (deb based)
  ansible.builtin.apt:
    name: linux-generic
    state: latest
    update_cache: yes
  when: ansible_os_family == "Debian"
  become: true

- name: Install InfiniBand support (rpm based)
  ansible.builtin.dnf:
    name: "@infiniband support"
    state: present
  when: ansible_os_family == "RedHat"
  become: true

- name: Load relevant kernel modules
  template:
    src: modules.conf.j2
    dest: /etc/modules-load.d/modules.conf
  become: true

- name: Switch cloud-init to alternative network renderer
  lineinfile:
    path: /etc/cloud/cloud.cfg
    regexp: "^    renderers:.*"
    line: "    renderers: ['sysconfig', 'network-manager', 'networkd']"
    state: present
  when: ansible_os_family == "Debian"
  become: true

- name: Clean up after ourselves
  ansible.builtin.apt:
    clean: yes
  become: yes
